services:
  # nginx
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  # php
  app:
    build:
      dockerfile: ./php/Dockerfile
    volumes:
      - ./app:/var/www/html

  # mysql
  db:
    image: mysql:8.3
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "4306:3306" #host:container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: translate-db
  # redis

volumes:
  mysqldata:
